import {
  GetStaticPathsResult,
  GetStaticPropsContext,
  InferGetStaticPropsType,
} from "next";
import { useRouter } from "next/router";
import { useQuery } from "react-query";
import { Main } from "../../components/Main";
import { ProductDetails } from "../../components/Product";

const getProduct = async (id: string) => {
  const data: Product = await (
    await fetch(`https://naszsklep-api.vercel.app/api/products/${id}`)
  ).json();
  return data;
};

const ProductsDetailsPage = () => {
  const router = useRouter();
  const { data, isLoading, error } = useQuery(
    "product",
    () => getProduct(router.query.productId as string),
    { enabled: Boolean(router.query.productId) }
  );
  if (isLoading) return <>is loading</>;
  if (!data || error) return <> is error</>;
  return (
    <Main>
      <ProductDetails
        data={{
          id: data.id,
          thumbnailAlt: data.title,
          thumbnailUrl: data.image,
          title: data.title,
          description: data.description,
          rating: data.rating.rate,
        }}
      />
    </Main>
  );
};

export default ProductsDetailsPage;

// Generated by https://quicktype.io

export interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  rating: {
    rate: number;
    count: number;
  };
  image: string;
  longDescription: string;
}
