import { InferGetStaticPropsType } from "next";
import { Main } from "../../components/Main";
import { ProductListItem } from "../../components/Product";

const ProductsPage = ({
  data,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <Main>
      <ul className=" grid  sm:grid-cols-2 md:grid-cols-3 gap-2 w-full">
        {data.map((product) => (
          <li key={product.id} className="shadow-xl ">
            <ProductListItem
              data={{
                id: product.id,
                thumbnailAlt: product.title,
                thumbnailUrl: product.image,
                title: product.title,
              }}
            />
          </li>
        ))}
      </ul>
    </Main>
  );
};

export default ProductsPage;

export const getStaticProps = async () => {
  const data: StoreApiResponse[] = await (
    await fetch("https://fakestoreapi.com/products/")
  ).json();

  return {
    props: {
      data,
    },
  };
};

// Generated by https://quicktype.io

export interface StoreApiResponse {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    rate: number;
    count: number;
  };
}
